### PR TITLE
updated dependencies and phantomjs version

### PR DESCRIPTION
**Pull request by trodrigues**

### CODE REVIEW

**Comment by jeromeetienne** [comment]
hmm have you tested ? i ask because i cant test it, so it would be blind trust :)

**Comment by trodrigues** [comment]
Yes I have, and currently using it to run unit tests on a continuous integration server. But this was on 10.4 LTS, not on the more recent ubuntu version. I could setup a VM with the latest and give it a try if you'd like, but it shouldn't be very different.

**Comment by jeromeetienne** [comment]
ok merged then :)

**Comment by trodrigues** [comment]
thanks :)

**Pull request merged**
